name: Lint, Test, and Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Deploy Project
        run: |
          npm run build
          echo "Deploying..."
